### ISSUE TITLE
problem when running 'python train_rl_agent.py'

### ISSUE THREAD

**Issue by xiulilee** [Traffic-Alpha/LLM-Assisted-Light#3] opened 2024-04-12 12:21 UTC
So there is no file named 'train_rl_agent.py' in TSCRL, Do you know if there are any problems with this? Thanks.

**Comment by wmn7** [comment] 2024-04-12 17:43
Hello,

Apologies for the confusion in the README.md, the RL code is indeed located at [sb3_ppo.py](https://github.com/Traffic-Alpha/LLM-Assisted-Light/blob/main/TSCRL/sb3_ppo.py), not `train_rl_agent.py` as previously mentioned. I will update the README.md accordingly.

Please note that this code is based on the [TransSimHub](https://github.com/Traffic-Alpha/TransSimHub) framework, which you should install correctly (the framework is currently in rapid development, and **you are welcome to join our discussion group for timely feedback on any issues**).

Thank you very much for bringing this to our attention.

**Comment by xiulilee** [comment] 2024-04-13 11:10
Thank you very much for your reply, I have installed TransSimHub according to the official documentation.
Do you mean to run the file sb3_ppo.py? I ran the file but it reported an error at line 32: TypeError: set_logger() got an unexpected keyword argument 'log_level'
Do you have any clue about this issue? Hope to hear from you soon, thanks a lot.

**Comment by wmn7** [comment] 2024-04-13 16:46
Hello,

Regarding the `set_logger` function, the supported parameters are now `file_log_level` and `terminal_log_level`, instead of `log_level`. This change allows for separate log level settings for file and terminal outputs.

This update was part of the recent changes in TransSimHub, which you can view here: https://github.com/Traffic-Alpha/TransSimHub/commit/925c96e2fcc3c62fae2ad2f0503942fe64cea4a4.

We apologize for any inconvenience caused by the lack of timely documentation updates. **Our main focus has been on the development of TransSimHub, which may result in slower updates elsewhere.**

Best regards,

**Comment by xiulilee** [comment] 2024-04-13 17:21
Thank you for your reply, I have just noticed the file_log and terminal_log in the code as well, thanks for your reply and all the best in hospitalizing your work in progress.

**Comment by wmn7** [comment] 2024-04-14 10:17
If there are no additional concerns, I'll proceed to close this issue.

Feel free to execute the code. Despite the slower execution speed, you should find the performance quite satisfactory, as we've invested significant effort in fine-tuning the prompts.

**Closed as completed** 2024-04-15 08:00 UTC
